### ISSUE TITLE
I was not able to receive my "received_image.jpg" image inside the pod 

### ISSUE THREAD

**Issue by srinu49** [openfaas-incubator/mqtt-connector#9]
## My actions before raising this issue
Published an image in to  "/testmqtt/pushimage1" MQTT topic 
It will trigger another function "mqttsubscribeimage"

## Expected Behaviour
"received_image.jpg" should be expected inside the pod

## Current Behaviour
Not able to find the "received_image.jpg".

## Steps to Reproduce (for bugs)
mqttsubscribeimage  function handler code  (handler.py)   (python3-flask-debian docker file used)
.........................................................................................

from PIL import Image 
import io
import json
import os
import uuid
import time
import paho.mqtt.client as mqtt

def on_message(client, userdata, message):
      
    open('received_image.jpg','wb').write(message.payload)
  

def handle(req):

    client = mqtt.Client("ipaddress_of_my_system:1883", transport="tcp")
    
    broker = "ipaddress_of_my_system"
    port = 1883

    client.connect(broker, port)

   
    print("connected to broker")
    client.loop_start() 
    
    client.subscribe("/testmqtt/pushimage1")   
    
    client.on_message = on_message

    
    time.sleep(1000)
    client.loop_forever()
    return req
    

 requirements.txt  file
.......................................................
 paho-mqtt
pillow==7.0.0

In mqttsubscribeimage function logs
..................................................................................
 I can see only -->  POST / - 200 OK - ContentLength: 50223  

## Your Environment
Running inside Minikube

**Comment by alexellis** [comment]
Hi,

Thanks for the interest in OpenFaaS.

I'd suggest you take the course I wrote for the LF/CNCF on OpenFaaS which uses MQTT and Python.

https://docs.openfaas.com/tutorials/training/#kubernetes-at-the-edge-with-k3s

That will show you how to achieve this goal using the MQTT connector

We would also need all test to be formatted properly or uploaded to a GitHub repo with a README with step by step instructions, if you expect us to try and run your code and help you. Otherwise, we aren't going to be able to help, unfortunately.

I'll close this until you've taken the course and corrected your code, and provided a full code repo. At which point, if you are still having issues, I'm happy to reopen it and continue the discussion.



Alex
